#!/usr/bin/env python3
"""Generate manuscript tables and numeric macros from machine-readable reports.

The manuscript's primary evidence is the true-dimension ablation:
Online (23D), RED21 (gravity removed), RED20 (accelerometer bias removed),
and RED18 (both removed).  Runtime correction-nulling results are used only
to quantify the proxy's validity.  The cross-estimator extension is read from
report/strengthening_20260831.json and remains a separate descriptive
population.  The final direction-observation campaign is read from the same
audited report; the earlier nominal sweep remains in liosam_direction.json.
The matched 23D-to-21D active-subspace switch is read from warm_fixg21.json.
Scale-aware equivalence sensitivity checks are read from
equivalence_sensitivity.json.
The outcome-locked four-manifold dynamic-start completion is read from
dynamic_init_factorial.json; its complete estimator failures remain outcomes
and are not folded into ordinary accuracy summaries.
"""
import json
import math
import re
import sys
from pathlib import Path

import numpy as np
from scipy import stats

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "paper" / "tables"
OUT.mkdir(parents=True, exist_ok=True)

CORE = [
    ("ntu_day_01_os1", "ntu-day-01"),
    ("ntu_day_02_os1", "ntu-day-02"),
    ("ntu_day_10_os1", "ntu-day-10"),
    ("ntu_night_04_os1", "ntu-night-04"),
    ("ntu_night_13_os1", "ntu-night-13"),
    ("kth_day_10_os1", "kth-day-10"),
    ("kth_night_05_os1", "kth-night-05"),
    ("tuhh_day_02_os1", "tuhh-day-02"),
    ("tuhh_day_04_os1", "tuhh-day-04"),
    ("tuhh_night_09_os1", "tuhh-night-09"),
    ("IndoorOffice1", "tiers-office"),
    ("hall_05_run", "m2dgr-hall"),
]
METHODS = ("A", "RED21", "RED20", "RED18")
DIM = {"A": 23, "RED21": 21, "RED20": 20, "RED18": 18}


def load():
    return json.loads((ROOT / "report" / "summary.json").read_text())["sequences"]


def load_strengthening():
    path = ROOT / "report" / "strengthening_20260831.json"
    data = json.loads(path.read_text())
    if data.get("status") != "completed_with_documented_failed_outcomes":
        raise RuntimeError("strengthening campaign is not in its final audited state")
    return data


def liosam_state_sequences(strengthening):
    block = strengthening["liosam_new_sequences"]
    sequences = block["previous_sequences"] + block["new_sequences"]
    if len(sequences) != block["total_sequence_units"]:
        raise RuntimeError("LIO-SAM state-ablation sequence count is inconsistent")
    return sequences


def usable(rec):
    return rec.get("usable", True) is not False


def repeat_values(runs, method, metric, include_repeats=True):
    values = []
    pattern = re.compile(rf"^{re.escape(method)}_r\d+$")
    for name, rec in runs.items():
        if name != method and not (include_repeats and pattern.match(name)):
            continue
        if usable(rec) and rec.get(metric) is not None:
            values.append(float(rec[metric]))
    return values


def med(runs, method, metric, include_repeats=True):
    values = repeat_values(runs, method, metric, include_repeats)
    return float(np.median(values)) if values else None


def fmt_ate(value):
    if value is None:
        return "--"
    return f"{value:.3f}" if value < 1 else f"{value:.2f}"


def pct(value):
    return f"{value:+.1f}"


def main_table(S):
    rows = []
    for seq, label in CORE:
        entry = S[seq]
        runs = entry["runs"]
        length = entry["gt"]["path_len_m"]
        a_z = runs["A"]["rmse_z_m"]
        a_ate = runs["A"]["ate_rmse_m"]
        cells = [f"{100000.0 * a_z / length:.1f}", fmt_ate(a_ate)]
        for method in ("RED21", "RED20", "RED18"):
            dz = 100 * (runs[method]["rmse_z_m"] / a_z - 1)
            date = 100 * (runs[method]["ate_rmse_m"] / a_ate - 1)
            cells.extend((pct(dz), pct(date)))
        rows.append(f"{label} & " + " & ".join(cells) + r" \\")
        if seq in {"ntu_night_13_os1", "kth_night_05_os1",
                   "tuhh_night_09_os1", "IndoorOffice1"}:
            rows.append(r"\addlinespace[1.5pt]")

    summary_cells = ["--", "--"]
    for method in ("RED21", "RED20", "RED18"):
        dz = paired_effects(S, method, "rmse_z_m")
        date = paired_effects(S, method, "ate_rmse_m")
        summary_cells.extend((pct(100 * np.median(dz - 1)),
                              pct(100 * np.median(date - 1))))
    rows.append(r"\midrule")
    rows.append(r"\textbf{Median paired $\Delta$} & "
                + " & ".join(summary_cells) + r" \\")

    tex = r"""% Auto-generated by scripts/make_tables.py; do not edit.
\begin{tabular}{@{}l rr rr rr rr@{}}
\toprule
& \multicolumn{2}{c}{\methodA{} absolute}
& \multicolumn{2}{c}{\methodG{} $\Delta$}
& \multicolumn{2}{c}{\methodB{} $\Delta$}
& \multicolumn{2}{c}{\methodGB{} $\Delta$} \\
\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}\cmidrule(lr){8-9}
Sequence & $e_z$ & ATE & RMSE$_z$ & ATE & RMSE$_z$ & ATE & RMSE$_z$ & ATE \\
& [mm/100\,m] & [m] & \multicolumn{6}{c}{paired change [\%]} \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
"""
    (OUT / "t1_main.tex").write_text(tex)
    print(f"t1_main.tex: {len(CORE)} sequences")


def nominal_evidence_table(S):
    """Compact main-paper table for nominal structural ablations."""
    fast_rows = []
    for method, label in (
        ("RED21", r"\methodG{}"),
        ("RED20", r"\methodB{}"),
        ("RED18", r"\methodGB{}"),
    ):
        z = 100 * (paired_effects(S, method, "rmse_z_m") - 1)
        ate = 100 * (paired_effects(S, method, "ate_rmse_m") - 1)
        fast_rows.append(
            f"{label} & {DIM[method]} & "
            rf"\nominalpair{{{np.median(z):+.1f}}}{{{np.median(ate):+.1f}}} & "
            f"$[{z.min():+.1f},{z.max():+.1f}]$ & "
            f"$[{ate.min():+.1f},{ate.max():+.1f}]$ " + r"\\"
        )
    fast_n = len(paired_effects(S, "RED21", "rmse_z_m"))

    liosam_sequences = liosam_state_sequences(load_strengthening())
    sequence_labels = {
        "m2dgr-hall05": "Hall05",
        "mcd_tuhh_day_04": "TUHH d04",
        "ntu_day_02": "NTU d02",
        "tuhh_night_09": "TUHH n09",
    }
    lio_rows = []
    for entry in liosam_sequences:
        runs = entry["runs"]
        baseline = runs["FG-BA"]
        cells = []
        for method in ("FG-B0", "GE-BA", "GE-B0"):
            z = 100 * (runs[method]["rmse_z_m"] / baseline["rmse_z_m"] - 1)
            ate = 100 * (runs[method]["ate_rmse_m"] / baseline["ate_rmse_m"] - 1)
            cells.append(rf"\nominalpair{{{z:+.2f}}}{{{ate:+.2f}}}")
        lio_rows.append(
            f"{sequence_labels[entry['sequence']]} & "
            + " & ".join(cells) + " " + r"\\"
        )

    tex = r"""% Auto-generated by scripts/make_tables.py; do not edit.
\begingroup
\renewcommand{\arraystretch}{1.06}
\newcommand{\nominalpair}[2]{\makebox[2.6em][r]{$#1$}\,$/$\,\makebox[2.6em][l]{$#2$}}
\begin{tabular*}{\columnwidth}{@{\extracolsep{\fill}}lcccc@{}}
\toprule
\rowcolor{TableBand}
\multicolumn{5}{@{}l}{\textsc{FAST-LIO2}\enspace paired change vs. \methodA{} [\%], $n=""" + str(fast_n) + r"""$} \\
Configuration & dim. & median $z$/ATE & range $z$ & range ATE \\
\midrule
""" + "\n".join(fast_rows) + r"""
\bottomrule
\end{tabular*}

\vspace{3pt}
\begin{tabular*}{\columnwidth}{@{\extracolsep{\fill}}lccc@{}}
\rowcolor{TableBand}
\multicolumn{4}{@{}l}{\textsc{LIO-SAM}\enspace paired $\Delta z/\Delta$ATE vs. \lsFGBA{} [\%]} \\
Sequence & \lsFGBZ{} & \lsGEBA{} & \lsGEBZ{} \\
\midrule
""" + "\n".join(lio_rows) + r"""
\bottomrule
\end{tabular*}
\endgroup
"""
    (OUT / "t1_nominal.tex").write_text(tex)
    print("t1_nominal.tex")


def operating_boundary_table(S):
    """Exact Online scale and paired FixG response across LiDAR outages."""
    warm = json.loads((ROOT / "report" / "warm_fixg21.json").read_text())
    groups = [
        (r"\textsc{Vehicle}\enspace continuous correction", [
            ("nominal", "ntu_day_10_os1", False),
            ("range 20 m", "ntu_day_10_range20", False),
            (r"FoV $\pm60^\circ$", "ntu_day_10_fov60", False),
        ]),
        (r"\textsc{Vehicle}\enspace dropout per 20 s", [
            ("1 s/20 s", "ntu_day_10_drop1x20", False),
            ("2 s/20 s", "ntu_day_10_drop2x20", True),
            ("3 s/20 s", "ntu_day_10_drop3x20", True),
            ("5 s/20 s", "ntu_day_10_drop5x20", False),
        ]),
        (r"\textsc{Handheld}\enspace dropout per 20 s", [
            ("2 s/20 s", "tuhh_day_04_drop2x20", False),
            ("3 s/20 s", "tuhh_day_04_drop3x20", False),
            ("5 s/20 s", "tuhh_day_04_drop5x20", False),
        ]),
    ]
    rows = []
    for group_index, (group, specs) in enumerate(groups):
        if group_index:
            rows.append(r"\addlinespace[2pt]")
        rows.append(r"\rowcolor{TableBand}")
        rows.append(rf"\multicolumn{{5}}{{@{{}}l}}{{{group}}} \\")
        for severity, seq, repeats in specs:
            runs = S[seq]["runs"]
            a_z = med(runs, "A", "rmse_z_m", repeats)
            a_ate = med(runs, "A", "ate_rmse_m", repeats)
            dz = effect(S, seq, "RED21", "rmse_z_m", repeats)
            date = effect(S, seq, "RED21", "ate_rmse_m", repeats)
            n = len(repeat_values(runs, "A", "rmse_z_m", repeats))
            rows.append(
                f"{severity} & ${fmt_ate(a_z)}/{fmt_ate(a_ate)}$ & "
                f"${dz:+.1f}$ & ${date:+.1f}$ & {n} " + r"\\"
            )

    rows.append(r"\addlinespace[2pt]")
    rows.append(r"\rowcolor{TableBand}")
    rows.append(
        r"\multicolumn{5}{@{}l}{\textsc{Matched posterior switch}\enspace "
        r"dropout--clean interaction [m]} \\"
    )
    for label in ("vehicle", "handheld"):
        trajectory = warm["trajectories"][label]
        repeat = trajectory["repeatability"]["summary"]["interaction"]
        phase = trajectory["phase_robustness"]["summary"]
        z_rep = repeat["rmse_z_m"]["absolute_difference_in_differences"]["median"]
        a_rep = repeat["ate_rmse_m"]["absolute_difference_in_differences"]["median"]
        rows.append(
            f"{label} repeats & -- & ${z_rep:+.2f}$ & ${a_rep:+.2f}$ & 3 " + r"\\"
        )
        z_phase = phase["rmse_z_m"]["absolute_difference_in_differences"]["range"]
        a_phase = phase["ate_rmse_m"]["absolute_difference_in_differences"]["range"]
        rows.append(
            f"{label} phases & -- & $[{z_phase[0]:+.2f},{z_phase[1]:+.2f}]$ & "
            f"$[{a_phase[0]:+.2f},{a_phase[1]:+.2f}]$ & 3 " + r"\\"
        )

    tex = r"""% Auto-generated by scripts/make_tables.py; do not edit.
\begin{tabular}{@{}lcccc@{}}
\toprule
Condition & \methodA{} $z$/ATE [m] & $\Delta z$ [\%] & $\Delta$ATE [\%] & $n$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
"""
    (OUT / "t2_operating.tex").write_text(tex)
    print("t2_operating.tex")


def boundary_table(S):
    rows = []
    for seconds in (0, 1, 2, 3, 5):
        seq = "ntu_day_10_os1" if seconds == 0 else f"ntu_day_10_drop{seconds}x20"
        entry = S[seq]
        runs = entry["runs"]
        repeats = seconds in (2, 3)
        a_z = med(runs, "A", "rmse_z_m", repeats)
        a_ate = med(runs, "A", "ate_rmse_m", repeats)
        cells = [f"{a_z:.2f}", f"{a_ate:.2f}"]
        for method in ("RED21", "RED20", "RED18"):
            z = med(runs, method, "rmse_z_m", repeats)
            ate = med(runs, method, "ate_rmse_m", repeats)
            cells.extend((pct(100 * (z / a_z - 1)), pct(100 * (ate / a_ate - 1))))
        rows.append(f"{seconds}/20 & " + " & ".join(cells) + r" \\")

    tex = r"""% Auto-generated by scripts/make_tables.py; do not edit.
\begin{tabular}{l rr rr rr rr}
\toprule
& \multicolumn{2}{c}{\methodA{} absolute [m]}
& \multicolumn{2}{c}{\methodG{} $\Delta$ [\%]}
& \multicolumn{2}{c}{\methodB{} $\Delta$ [\%]}
& \multicolumn{2}{c}{\methodGB{} $\Delta$ [\%]} \\
\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}\cmidrule(lr){8-9}
Dropout [s/20s] & RMSE$_z$ & ATE & RMSE$_z$ & ATE & RMSE$_z$ & ATE & RMSE$_z$ & ATE \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
"""
    (OUT / "t2_boundary.tex").write_text(tex)
    print("t2_boundary.tex")


def validity_table(S):
    rows = []
    specs = [
        ("gravity", "B", "RED21", 2),
        ("$\\mathbf{b}_a$", "D", "RED20", 3),
        ("both", "C", "RED18", 5),
    ]
    for label, proxy, reduced, removed_dim in specs:
        dz, da = [], []
        for seq, _ in CORE:
            runs = S[seq]["runs"]
            if proxy not in runs or reduced not in runs:
                continue
            a = runs["A"]
            if not (usable(runs[proxy]) and usable(runs[reduced])):
                continue
            dz.append(100 * (runs[reduced]["rmse_z_m"] - runs[proxy]["rmse_z_m"])
                      / a["rmse_z_m"])
            da.append(100 * (runs[reduced]["ate_rmse_m"] - runs[proxy]["ate_rmse_m"])
                      / a["ate_rmse_m"])
        rows.append(f"{label} & {DIM[reduced]} & {len(dz)} & "
                    f"{pct(float(np.median(dz)))} & {pct(float(np.median(da)))} " + r"\\")

    tex = r"""% Auto-generated by scripts/make_tables.py; do not edit.
\begin{tabular}{lrrrr}
\toprule
Removed & dimension & $n$ & $\Delta$RMSE$_z$ [pp] & $\Delta$ATE [pp] \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
"""
    (OUT / "t3_validity.tex").write_text(tex)
    print("t3_validity.tex")


def imu_stress_table(S):
    rows = []
    sequences = (
        ("ntu_day_10_os1", "ntu-day-10"),
        ("ntu_night_04_os1", "ntu-night-04"),
    )
    scales = (("0p01", "0.01"), ("0p1", "0.1"), ("1", "1"), ("10", "10"))
    for seq, seq_label in sequences:
        runs = S[seq]["runs"]
        for index, (run_label, scale_label) in enumerate(scales):
            online = runs[f"A_tdim_imuw{run_label}"]
            red21 = runs[f"RED21_tdim_imuw{run_label}"]
            dz = 100 * (red21["rmse_z_m"] / online["rmse_z_m"] - 1)
            date = 100 * (red21["ate_rmse_m"] / online["ate_rmse_m"] - 1)
            label = seq_label if index == 0 else ""
            rows.append(
                f"{label} & {scale_label} & {online['rmse_z_m']:.2f} & "
                f"{red21['rmse_z_m']:.2f} & {pct(dz)} & "
                f"{online['ate_rmse_m']:.2f} & {red21['ate_rmse_m']:.2f} & "
                f"{pct(date)} " + r"\\"
            )
        if seq != sequences[-1][0]:
            rows.append(r"\addlinespace[1pt]")

    tex = r"""% Auto-generated by scripts/make_tables.py; do not edit.
\begin{tabular}{ll rrr rrr}
\toprule
& & \multicolumn{3}{c}{RMSE$_z$} & \multicolumn{3}{c}{ATE} \\
\cmidrule(lr){3-5}\cmidrule(lr){6-8}
Sequence & noise scale & \methodA{} & \methodG{} & $\Delta$ [\%]
& \methodA{} & \methodG{} & $\Delta$ [\%] \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
"""
    (OUT / "t4_imuweight.tex").write_text(tex)
    print("t4_imuweight.tex")


def legacy_direction_factor_table():
    data = json.loads((ROOT / "report" / "liosam_direction.json").read_text())
    nominal = data["nominal"]

    def nominal_range(variant, level, field):
        values = [entry["runs"][f"{variant}_{level}"][field] for entry in nominal]
        return f"[{min(values):+.1f},{max(values):+.1f}]"

    def metric_cells(z_value, ate_value):
        return f"${z_value}$ & ${ate_value}$"

    nominal_rows = []
    for level, sigma in (("s0p5", "0.5"), ("s2", "2"), ("s5", "5")):
        nominal_rows.append(
            f"\\quad ${sigma}^\\circ$ & \\methodG{{}} & "
            f"{metric_cells(nominal_range('FG-BA', level, 'delta_rmse_z_pct_vs_off'), nominal_range('FG-BA', level, 'delta_ate_pct_vs_off'))} & "
            f"{len(nominal)} " + r"\\"
        )
    ge_z = []
    ge_ate = []
    for entry in nominal:
        for level in ("s0p5", "s2", "s5"):
            run = entry["runs"][f"GE-BA_{level}"]
            ge_z.append(run["delta_rmse_z_pct_vs_off"])
            ge_ate.append(run["delta_ate_pct_vs_off"])
    nominal_rows.append(
        r"\quad all weights & \methodA{} & "
        f"{metric_cells(f'[{min(ge_z):+.1f},{max(ge_z):+.1f}]', f'[{min(ge_ate):+.2f},{max(ge_ate):+.2f}]')} & "
        f"{len(nominal)} " + r"\\"
    )

    tuhh_rows = []
    drop2 = data["dropout"][0]["runs"]
    for variant in ("FG-BA", "GE-BA"):
        run = drop2[f"{variant}_s2"]
        tuhh_rows.append(
            f"\\quad 2 s & {'\\methodG{}' if variant == 'FG-BA' else '\\methodA{}'} & "
            f"{metric_cells(f'{run['delta_rmse_z_pct_vs_off']:+.1f}', f'{run['delta_ate_pct_vs_off']:+.1f}')} & "
            "1 " + r"\\"
        )
    drop3_repeats = data["dropout"][1]["repeatability"]
    drop3_valid = drop3_repeats["FG-BA_s2"]["valid_runs"]
    drop3_invalid = sum(key.startswith("FG-BA_s2_invalid")
                        for key in drop3_repeats)
    drop3_total = drop3_valid + drop3_invalid
    tuhh_rows.append(
        r"\quad 3 s & \methodG{} & \multicolumn{2}{c}{not identifiable} & "
        f"{drop3_valid}/{drop3_total} " + r"\\"
    )
    drop5 = data["dropout"][2]
    fg5 = drop5["runs"]["FG-BA_s2"]
    tuhh_rows.append(
        r"\quad 5 s & \methodG{} & "
        f"{metric_cells(f'{fg5['delta_rmse_z_pct_vs_off']:+.1f}', f'{fg5['delta_ate_pct_vs_off']:+.1f}')} & "
        "1 " + r"\\"
    )
    ge5 = drop5["repeatability"]["GE-BA"]
    z5 = ge5["delta_rmse_z_pct_range"]
    a5 = ge5["delta_ate_pct_range"]
    tuhh_rows.append(
        r"\quad 5 s & \methodA{} & "
        f"{metric_cells(f'[{z5[0]:+.0f},{z5[1]:+.0f}]', f'[{a5[0]:+.0f},{a5[1]:+.0f}]')} & "
        f"{ge5['paired_repeats']} " + r"\\"
    )

    hall_rows = []
    hall_pairs = data["hall05_dropout_factorial"]["paired_repeats"]
    hall = data["hall05_dropout_factorial"]["effects"]
    for variant in ("FG-BA", "GE-BA"):
        z = hall[f"{variant}_rmse_z_factor_effect_pct"]["range"]
        ate = hall[f"{variant}_ate_factor_effect_pct"]["range"]
        hall_rows.append(
            f"\\quad 5 s & {'\\methodG{}' if variant == 'FG-BA' else '\\methodA{}'} & "
            f"{metric_cells(f'[{z[0]:+.1f},{z[1]:+.1f}]', f'[{ate[0]:+.1f},{ate[1]:+.1f}]')} & "
            f"{hall_pairs} " + r"\\"
        )

    tex = r"""% Auto-generated by scripts/make_tables.py; do not edit.
\begingroup
\renewcommand{\arraystretch}{1.05}
\begin{tabular*}{\columnwidth}{@{\extracolsep{\fill}}llrrl@{}}
\toprule
Setting & $g$ state & $\Delta$RMSE$_z$ [\%] & $\Delta$ATE [\%] & $n$ \\
\midrule
\rowcolor{TableBand}
\multicolumn{5}{@{}l}{\textsc{Continuous correction}\enspace factor weight $\sigma_d$} \\
""" + "\n".join(nominal_rows) + r"""
\addlinespace[2pt]
\rowcolor{TableBand}
\multicolumn{5}{@{}l}{\textsc{TUHH handheld}\enspace dropout per 20 s} \\
""" + "\n".join(tuhh_rows) + r"""
\addlinespace[2pt]
\rowcolor{TableBand}
\multicolumn{5}{@{}l}{\textsc{Hall05}\enspace dropout per 20 s} \\
""" + "\n".join(hall_rows) + r"""
\bottomrule
\end{tabular*}
\endgroup
"""
    (OUT / "t5_direction.tex").write_text(tex)
    print("t5_direction.tex")


def direction_factor_table():
    """Final 5-s direction-factor campaign, including observed outcomes."""
    strengthening = load_strengthening()
    sequences = strengthening["liosam_dropout_weights"]["sequences"]
    by_name = {entry["sequence"]: entry["cells"] for entry in sequences}

    def rows_for(sequence):
        cells = by_name[sequence]
        rows = []
        for variant, state in (("FG-BA", r"\methodG{}"),
                               ("GE-BA", r"\methodA{}")):
            for level, sigma in (("s0p5", "0.5"), ("s2", "2"), ("s5", "5")):
                cell = cells[f"{variant}_{level}"]
                z = cell["delta_rmse_z_pct_vs_off"]["median"]
                ate = cell["delta_ate_pct_vs_off"]["median"]
                outcome = f"{cell['accuracy_repeats']}/{cell['requested_repeats']}"
                if cell["failed_repeats"]:
                    outcome += f"; {cell['failed_repeats']} R"
                if cell["arc_warning_repeats"]:
                    outcome += f"; {cell['arc_warning_repeats']} A"
                rows.append(
                    fr"${sigma}^\circ$ & {state} & ${z:+.1f}$ & "
                    f"${ate:+.1f}$ & {outcome} " + r"\\"
                )
        return rows

    hall_rows = rows_for("hall05")
    tuhh_rows = rows_for("tuhh_day04")
    tex = r"""% Auto-generated by scripts/make_tables.py; do not edit.
\begingroup
\renewcommand{\arraystretch}{1.05}
\begin{tabular*}{\columnwidth}{@{\extracolsep{\fill}}llrrl@{}}
\toprule
Weight & $g$ state & $\Delta$RMSE$_z$ [\%] & $\Delta$ATE [\%] & outcome \\
\midrule
\rowcolor{TableBand}
\multicolumn{5}{@{}l}{\textsc{Hall05}\enspace 5-s dropout per 20 s} \\
""" + "\n".join(hall_rows) + r"""
\addlinespace[2pt]
\rowcolor{TableBand}
\multicolumn{5}{@{}l}{\textsc{TUHH handheld}\enspace 5-s dropout per 20 s} \\
""" + "\n".join(tuhh_rows) + r"""
\bottomrule
\end{tabular*}
\endgroup
"""
    (OUT / "t5_direction.tex").write_text(tex)
    print("t5_direction.tex")


def paired_effects(S, method, metric):
    ratios = []
    for seq, _ in CORE:
        runs = S[seq]["runs"]
        ratios.append(runs[method][metric] / runs["A"][metric])
    return np.asarray(ratios, dtype=float)


def interaction(S, metric):
    values = []
    for seq, _ in CORE:
        r = S[seq]["runs"]
        a = r["A"][metric]
        value = ((r["RED18"][metric] - a) - (r["RED21"][metric] - a)
                 - (r["RED20"][metric] - a)) / a
        values.append(100 * value)
    return np.asarray(values)


def effect(S, seq, method, metric, repeats=False):
    runs = S[seq]["runs"]
    a = med(runs, "A", metric, repeats)
    x = med(runs, method, metric, repeats)
    return 100 * (x / a - 1)


def macro(name, value):
    if value is None:
        return f"\\newcommand{{\\{name}}}{{\\todo{{{name}}}}}"
    return f"\\newcommand{{\\{name}}}{{{value}\\xspace}}"


def fmt_p(value):
    return "$<10^{-4}$" if value < 1e-4 else f"${value:.3f}$"


def stats_macros(S):
    g_z = paired_effects(S, "RED21", "rmse_z_m")
    g_a = paired_effects(S, "RED21", "ate_rmse_m")
    b_z = paired_effects(S, "RED20", "rmse_z_m")
    gb_z = paired_effects(S, "RED18", "rmse_z_m")
    strengthening = load_strengthening()
    equivalence = json.loads(
        (ROOT / "report" / "equivalence_sensitivity.json").read_text()
    )
    if equivalence.get("status") != "complete_existing_results_only":
        raise RuntimeError("equivalence sensitivity analysis is not validated")
    liosam_sequences = liosam_state_sequences(strengthening)
    reproduction = strengthening["fastlio_reproduction"]["population"]
    equivalence_primary = equivalence["primary"]
    equivalence_repro = equivalence["launch_specific_reproduction"]
    equivalence_family = equivalence["trajectory_family_balanced"]["metrics"]
    hall_scale = equivalence["small_baseline_example"]["metrics"]
    final_direction = {
        entry["sequence"]: entry["cells"]
        for entry in strengthening["liosam_dropout_weights"]["sequences"]
    }
    direction = json.loads((ROOT / "report" / "liosam_direction.json").read_text())
    warm_fixg21 = json.loads((ROOT / "report" / "warm_fixg21.json").read_text())
    state_complexity = json.loads(
        (ROOT / "report" / "state_complexity.json").read_text()
    )
    runtime = json.loads((ROOT / "report" / "runtime_benchmark.json").read_text())
    dynamic_init = json.loads((ROOT / "report" / "dynamic_init.json").read_text())
    dynamic_init_fast = json.loads(
        (ROOT / "report" / "dynamic_init_fast.json").read_text()
    )
    dynamic_init_factorial = json.loads(
        (ROOT / "report" / "dynamic_init_factorial.json").read_text()
    )
    coupled_state_init = json.loads(
        (ROOT / "report" / "coupled_state_init.json").read_text()
    )
    if dynamic_init_fast.get("status") != "completed_structural_and_gt_gates_pass":
        raise RuntimeError("stronger-motion initialization campaign is not validated")
    if dynamic_init_factorial.get("status") != (
            "completed_structural_gates_with_retained_estimator_failures"):
        raise RuntimeError("dynamic-start factorial campaign is not validated")
    if coupled_state_init.get("status") != "completed_structural_gates_pass":
        raise RuntimeError("coupled-state allocation campaign is not validated")
    if coupled_state_init.get("planned_runs") != coupled_state_init.get("included_runs"):
        raise RuntimeError("coupled-state allocation campaign is incomplete")
    if state_complexity.get("end_to_end_profiled") is not False:
        raise RuntimeError("state complexity estimate must not claim profiling")
    fixg_complexity = state_complexity["estimates"]["FixG"]
    runtime_summary = runtime["summary"]
    if runtime_summary["n_pairs"] != 3:
        raise RuntimeError("runtime benchmark requires three complete serial pairs")
    runtime_frames = {run["frames"] for run in runtime["runs"]}
    runtime_timed_frames = {run["timed_frames"] for run in runtime["runs"]}
    runtime_warmups = {run["warmup_scans_excluded"] for run in runtime["runs"]}
    if (len(runtime_frames) != 1 or len(runtime_timed_frames) != 1
            or len(runtime_warmups) != 1):
        raise RuntimeError("runtime frame-count gate failed")
    runtime_algebra = runtime_summary["paired_effects_pct"]["filter_algebra_pct"]
    runtime_core_saving = runtime_summary["paired_effects_pct"][
        "filter_algebra_saving_as_online_core_pct"
    ]
    runtime_core_median = runtime_summary["paired_effects_pct"]["core_median_pct"]
    runtime_workload_shares = runtime_summary["workload_shares_pct"]
    runtime_tree_values = [
        run["map_workload"]["mean_tree_size_at_scan_start"]
        for run in runtime["runs"]
    ]
    dynamic_vehicle = dynamic_init["aggregate"]["vehicle"]
    dynamic_handheld = dynamic_init["aggregate"]["handheld"]
    dynamic_records = [
        record for record in dynamic_init["records"]
        if record["regime"] == "dynamic"
    ]
    fast_dynamic_records = dynamic_init_fast["records"]
    factorial_records = dynamic_init_factorial["records"]
    factorial_low_rate = [
        record for record in factorial_records if record["regime"] == "dynamic"
    ]
    factorial_strong = [
        record for record in factorial_records
        if record["regime"] == "stronger_natural_motion"
    ]
    coupled_sequences = coupled_state_init["sequences"]
    coupled_handheld = [
        coupled_sequences["handheld"][sign]["paired"]
        for sign in ("plus", "minus")
    ]
    coupled_vehicle = [
        coupled_sequences["vehicle"][sign]["paired"]
        for sign in ("plus", "minus")
    ]

    def coupled_tail(field, runs):
        return np.asarray([run["last_10s"][field] for run in runs], dtype=float)

    coupled_initial_h_max = max(
        run["initial"]["effective_term_distance_to_base_mps2"]
        for run in coupled_handheld + coupled_vehicle
    )
    coupled_initial_h_exp = int(math.floor(math.log10(coupled_initial_h_max)))
    coupled_initial_h_mantissa = coupled_initial_h_max / (10 ** coupled_initial_h_exp)
    fast_vehicle_rescue = next(
        record for record in fast_dynamic_records
        if record["sequence"] == "ntu_day_10_fastinit_s189p471"
    )
    quiet_z = np.asarray([
        dynamic_init["aggregate"][platform]["quiet_effect_pct"]["rmse_z"]
        for platform in ("vehicle", "handheld")
    ])
    quiet_ate = np.asarray([
        dynamic_init["aggregate"][platform]["quiet_effect_pct"]["ate"]
        for platform in ("vehicle", "handheld")
    ])

    def pct_span(values):
        values = np.asarray(values, dtype=float)
        return f"{values.min():+.2f}\\% to {values.max():+.2f}\\%"

    warm_vehicle = warm_fixg21["trajectories"]["vehicle"]
    warm_handheld = warm_fixg21["trajectories"]["handheld"]

    def warm_effect(trajectory, condition, metric):
        return trajectory["repeatability"]["summary"][f"{condition}_effect"][metric][
            "percent"
        ]["median"]

    def warm_interaction_summary(trajectory, metric, source, statistic):
        if source == "repeatability":
            record = trajectory[source]["summary"]["interaction"][metric]
        else:
            record = trajectory[source]["summary"][metric]
        return record["absolute_difference_in_differences"][statistic]

    def metric_range(values, digits=2, unit=""):
        return f"[{values[0]:+.{digits}f},{values[1]:+.{digits}f}]{unit}"

    def liosam_ratios(numerator, denominator, metric):
        return np.asarray([
            entry["runs"][numerator][metric] /
            entry["runs"][denominator][metric]
            for entry in liosam_sequences
        ], dtype=float)

    liosam_g_z = liosam_ratios("GE-BA", "FG-BA", "rmse_z_m")
    liosam_g_ate = liosam_ratios("GE-BA", "FG-BA", "ate_rmse_m")
    liosam_both_z = liosam_ratios("FG-B0", "FG-BA", "rmse_z_m")
    liosam_both_ate = liosam_ratios("FG-B0", "FG-BA", "ate_rmse_m")

    def direction_nominal_values(variant, level, field):
        return np.asarray([
            entry["runs"][f"{variant}_{level}"][field]
            for entry in direction["nominal"]
        ], dtype=float)

    dir_fg_s05_z = direction_nominal_values("FG-BA", "s0p5", "delta_rmse_z_pct_vs_off")
    dir_fg_s2_z = direction_nominal_values("FG-BA", "s2", "delta_rmse_z_pct_vs_off")
    dir_fg_s2_ate = direction_nominal_values("FG-BA", "s2", "delta_ate_pct_vs_off")
    dir_ge_ate = np.asarray([
        entry["runs"][f"GE-BA_{level}"]["delta_ate_pct_vs_off"]
        for entry in direction["nominal"] for level in ("s0p5", "s2", "s5")
    ], dtype=float)
    dir_drop2 = direction["dropout"][0]["runs"]
    dir_drop3 = direction["dropout"][1]["repeatability"]
    dir_drop5 = direction["dropout"][2]["repeatability"]["GE-BA"]
    hall_direction = direction["hall05_dropout_factorial"]
    hall_final = final_direction["hall05"]
    tuhh_final = final_direction["tuhh_day04"]
    dropout_windows = json.loads((ROOT / "report" / "dropout_windows.json").read_text())

    def tost(ratios, margin=0.05):
        lr = np.log(ratios)
        d = math.log(1 + margin)
        return max(stats.ttest_1samp(lr, -d, alternative="greater").pvalue,
                   stats.ttest_1samp(lr, d, alternative="less").pvalue)

    def mean_ci90_text(ratios):
        lr = np.log(ratios)
        half = stats.t.ppf(0.95, len(lr) - 1) * stats.sem(lr)
        lo, center, hi = 100 * (np.exp((lr.mean() - half, lr.mean(),
                                        lr.mean() + half)) - 1)
        return f"{center:+.2f}\\% [{lo:+.2f}, {hi:+.2f}]\\%"

    def reported_ci90_text(record):
        lo, hi = record["ci90_pct"]
        return (f"{record['mean_paired_effect_pct']:+.2f}\\% "
                f"[{lo:+.2f}, {hi:+.2f}]\\%")

    def final_cell(sequence, variant, level):
        source = hall_final if sequence == "hall" else tuhh_final
        return source[f"{variant}_{level}"]

    def final_median(sequence, variant, level, metric):
        return final_cell(sequence, variant, level)[metric]["median"]

    def range_text(ratios):
        values = 100 * (ratios - 1)
        return f"{values.min():+.1f}--{values.max():+.1f}\\%"

    def range_text2(ratios):
        values = 100 * (ratios - 1)
        return f"{values.min():+.2f}--{values.max():+.2f}\\%"

    grav = [S[seq]["runs"]["A"].get("grav_angle_max_deg") for seq, _ in CORE]
    grav = [x for x in grav if x is not None]
    lengths = [S[seq]["gt"]["path_len_m"] for seq, _ in CORE]
    iz = interaction(S, "rmse_z_m")
    ia = interaction(S, "ate_rmse_m")
    proxy_ba = []
    for seq, _ in CORE:
        runs = S[seq]["runs"]
        if "D" in runs and "RED20" in runs:
            proxy_ba.append(100 * (runs["RED20"]["rmse_z_m"] - runs["D"]["rmse_z_m"])
                            / runs["A"]["rmse_z_m"])
    protocol = json.loads((ROOT / "report" / "summary.json").read_text())["protocol"]
    hall = S["hall_05_run"]
    hall_a = hall["runs"]["A"]
    hall_both = hall["runs"]["RED18"]
    hall_ez = 100000.0 * hall_a["rmse_z_m"] / hall["gt"]["path_len_m"]

    stress_sequences = ("ntu_day_10_os1", "ntu_night_04_os1")
    stress_labels = ("0p01", "0p1", "1", "10")

    def stress_effects(seq, metric):
        runs = S[seq]["runs"]
        values = []
        for label in stress_labels:
            a = runs[f"A_tdim_imuw{label}"][metric]
            g = runs[f"RED21_tdim_imuw{label}"][metric]
            values.append(100 * (g / a - 1))
        return np.asarray(values)

    day_z = stress_effects("ntu_day_10_os1", "rmse_z_m")
    day_ate = stress_effects("ntu_day_10_os1", "ate_rmse_m")
    night_z = stress_effects("ntu_night_04_os1", "rmse_z_m")
    night_ate = stress_effects("ntu_night_04_os1", "ate_rmse_m")
    attitude_delta = []
    for seq in stress_sequences:
        runs = S[seq]["runs"]
        for label in stress_labels:
            a = runs[f"A_tdim_imuw{label}"]
            g = runs[f"RED21_tdim_imuw{label}"]
            attitude_delta.extend((
                abs(g["rmse_roll_deg"] - a["rmse_roll_deg"]),
                abs(g["rmse_pitch_deg"] - a["rmse_pitch_deg"]),
            ))

    init_sequences = ("ntu_day_10_os1", "tuhh_day_04_os1")
    init_labels = ("0p5", "1", "2")

    def init_effects(metric):
        values = []
        for seq in init_sequences:
            runs = S[seq]["runs"]
            for label in init_labels:
                a = runs[f"A_tdim_err{label}"][metric]
                g = runs[f"RED21_tdim_err{label}"][metric]
                values.append(100 * (g / a - 1))
        return np.asarray(values)

    init_z = init_effects("rmse_z_m")
    init_ate = init_effects("ate_rmse_m")
    init_attitude_delta = []
    for seq in init_sequences:
        runs = S[seq]["runs"]
        for label in init_labels:
            a = runs[f"A_tdim_err{label}"]
            g = runs[f"RED21_tdim_err{label}"]
            init_attitude_delta.extend((
                abs(g["rmse_roll_deg"] - a["rmse_roll_deg"]),
                abs(g["rmse_pitch_deg"] - a["rmse_pitch_deg"]),
            ))

    lines = [
        "% Auto-generated by scripts/make_tables.py; do not edit.",
        macro("NumCoreSeq", len(CORE)),
        macro("NumCoreRuns", len(CORE) * len(METHODS)),
        macro(
            "FixGStateWorkReduction",
            f"{fixg_complexity['quadratic_reduction_pct_vs_online']:.1f}--"
            f"{fixg_complexity['cubic_reduction_pct_vs_online']:.1f}\\%",
        ),
        macro("NumRuntimePairs", runtime_summary["n_pairs"]),
        macro("NumRuntimeScans", next(iter(runtime_frames))),
        macro("NumRuntimeTimedScans", next(iter(runtime_timed_frames))),
        macro("NumRuntimeWarmupScans", next(iter(runtime_warmups))),
        macro("NumDynamicInitPairs", len(dynamic_init["records"])),
        macro("NumDynamicInitPhases", dynamic_init["design"]["dynamic_phases_per_trajectory"]),
        macro("DynamicQuietZRange", pct_span(quiet_z)),
        macro("DynamicQuietATERange", pct_span(quiet_ate)),
        macro("DynamicVehicleZRange", pct_span(dynamic_vehicle["dynamic_effect_pct"]["rmse_z"])),
        macro("DynamicVehicleATERange", pct_span(dynamic_vehicle["dynamic_effect_pct"]["ate"])),
        macro("DynamicHandheldZRange", pct_span(dynamic_handheld["dynamic_effect_pct"]["rmse_z"])),
        macro("DynamicHandheldATERange", pct_span(dynamic_handheld["dynamic_effect_pct"]["ate"])),
        macro("DynamicInitAngleRange", (
            f"{min(record['selection_window']['apparent_gravity_angle_deg'] for record in dynamic_records):.2f}--"
            f"{max(record['selection_window']['apparent_gravity_angle_deg'] for record in dynamic_records):.2f}$^\\circ$"
        )),
        macro("DynamicOnlineGMotionRange", (
            f"{min(record['metrics']['A']['grav_angle_max_deg'] for record in dynamic_records):.2f}--"
            f"{max(record['metrics']['A']['grav_angle_max_deg'] for record in dynamic_records):.2f}$^\\circ$"
        )),
        macro("NumFastDynamicInitPairs", len(fast_dynamic_records)),
        macro("NumFastDynamicInitRuns", 2 * len(fast_dynamic_records)),
        macro("NumDynamicFactorialPhases", len(factorial_records)),
        macro("NumDynamicFactorialRuns", len(factorial_records) * 4),
        macro("NumDynamicFactorialNewRuns", dynamic_init_factorial["design"]["new_runs"]),
        macro("NumCoupledStateRuns", coupled_state_init["included_runs"]),
        macro("NumCoupledStateTraj", coupled_state_init["trajectory_units"]),
        macro(
            "CoupledStateTiltDeg",
            f"{max(abs(v) for v in coupled_state_init['intervention']['gravity_tilt_deg']):.0f}",
        ),
        macro(
            "CoupledStateInitialBA",
            f"{max(run['initial']['ba_distance_to_base_mps2'] for run in coupled_handheld):.3f}\\,m/s$^2$",
        ),
        macro(
            "CoupledStateInitialHMax",
            f"${coupled_initial_h_mantissa:.1f}\\times10^{{{coupled_initial_h_exp}}}$"
            "\\,m/s$^2$",
        ),
        macro(
            "CoupledHhsGRange",
            f"{coupled_tail('gravity_angle_to_base_deg_median', coupled_handheld).min():.2f}--"
            f"{coupled_tail('gravity_angle_to_base_deg_median', coupled_handheld).max():.2f}$^\\circ$",
        ),
        macro(
            "CoupledHhsBARange",
            f"{coupled_tail('ba_distance_to_base_mps2_median', coupled_handheld).min():.3f}--"
            f"{coupled_tail('ba_distance_to_base_mps2_median', coupled_handheld).max():.3f}\\,m/s$^2$",
        ),
        macro(
            "CoupledHhsHRange",
            f"{coupled_tail('effective_term_distance_to_base_mps2_median', coupled_handheld).min():.4f}--"
            f"{coupled_tail('effective_term_distance_to_base_mps2_median', coupled_handheld).max():.4f}\\,m/s$^2$",
        ),
        macro(
            "CoupledHhsPoseRange",
            f"{1000 * coupled_tail('position_distance_to_base_m_median', coupled_handheld).min():.1f}--"
            f"{1000 * coupled_tail('position_distance_to_base_m_median', coupled_handheld).max():.1f}\\,mm",
        ),
        macro(
            "CoupledVehGRange",
            f"{coupled_tail('gravity_angle_to_base_deg_median', coupled_vehicle).min():.3f}--"
            f"{coupled_tail('gravity_angle_to_base_deg_median', coupled_vehicle).max():.3f}$^\\circ$",
        ),
        macro(
            "CoupledVehBARange",
            f"{coupled_tail('ba_distance_to_base_mps2_median', coupled_vehicle).min():.4f}--"
            f"{coupled_tail('ba_distance_to_base_mps2_median', coupled_vehicle).max():.4f}\\,m/s$^2$",
        ),
        macro("NumDynamicFixedBaFailurePhases", sum(
            not record["gates"]["accuracy_admitted"]["RED20"]
            or not record["gates"]["accuracy_admitted"]["RED18"]
            for record in factorial_low_rate
        )),
        macro("NumDynamicFixedBaFailureOutcomes", sum(
            not record["gates"]["accuracy_admitted"][method]
            for record in factorial_low_rate
            for method in ("RED20", "RED18")
        )),
        macro("NumStrongFixBaATEWorse", sum(
            record["contrasts"]["ate_rmse_m"]["fixba_vs_online"]["relative_pct"] > 0.4
            for record in factorial_strong
        )),
        macro("NumStrongFixBaBothWorse", sum(
            all(record["contrasts"][metric]["fixba_vs_online"]["relative_pct"] > 0.4
                for metric in ("rmse_z_m", "ate_rmse_m"))
            for record in factorial_strong
        )),
        macro("StrongFixBaATERange", pct_span([
            record["contrasts"]["ate_rmse_m"]["fixba_vs_online"]["relative_pct"]
            for record in factorial_strong
        ])),
        macro("FastDynamicInitAngleRange", (
            f"{min(record['selection_window']['apparent_gravity_angle_deg'] for record in fast_dynamic_records):.2f}--"
            f"{max(record['selection_window']['apparent_gravity_angle_deg'] for record in fast_dynamic_records):.2f}$^\\circ$"
        )),
        macro("FastDynamicGyroRange", (
            f"{min(record['selection_window']['mean_gyro_norm_radps'] for record in fast_dynamic_records):.3f}--"
            f"{max(record['selection_window']['mean_gyro_norm_radps'] for record in fast_dynamic_records):.3f}\\,rad/s"
        )),
        macro("FastDynamicOnlineGMotionRange", (
            f"{min(record['metrics']['A']['grav_angle_max_deg'] for record in fast_dynamic_records):.2f}--"
            f"{max(record['metrics']['A']['grav_angle_max_deg'] for record in fast_dynamic_records):.2f}$^\\circ$"
        )),
        macro("NumFastDynamicOnlineBothWins", sum(
            record["effects_fixg_minus_online"]["rmse_z"]["relative_pct"] > 0.4
            and record["effects_fixg_minus_online"]["ate"]["relative_pct"] > 0.4
            for record in fast_dynamic_records
        )),
        macro(
            "FastDynamicRescueOnlineZ",
            f"{fast_vehicle_rescue['metrics']['A']['rmse_z_m']:.3f}\\,m",
        ),
        macro(
            "FastDynamicRescueFixGZ",
            f"{fast_vehicle_rescue['metrics']['RED21']['rmse_z_m']:.3f}\\,m",
        ),
        macro(
            "FastDynamicRescueOnlineATE",
            f"{fast_vehicle_rescue['metrics']['A']['ate_rmse_m']:.3f}\\,m",
        ),
        macro(
            "FastDynamicRescueFixGATE",
            f"{fast_vehicle_rescue['metrics']['RED21']['ate_rmse_m']:.3f}\\,m",
        ),
        macro(
            "RuntimeOnlineAlgebraMs",
            f"{runtime_summary['per_method']['A']['filter_algebra_ms']['median']:.2f}\\,ms",
        ),
        macro(
            "RuntimeFixGAlgebraMs",
            f"{runtime_summary['per_method']['RED21']['filter_algebra_ms']['median']:.2f}\\,ms",
        ),
        macro("RuntimeAlgebraReduction", f"{-runtime_algebra['median']:.1f}\\%"),
        macro(
            "RuntimeAlgebraCoreShare",
            f"{runtime_workload_shares['filter_algebra_of_reported_core_pct']['median']:.2f}\\%",
        ),
        macro(
            "RuntimeMatchingCoreShare",
            f"{runtime_workload_shares['matching_of_reported_core_pct']['median']:.1f}\\%",
        ),
        macro("RuntimeAttributableCoreSaving", f"{runtime_core_saving['median']:.2f}\\%"),
        macro(
            "RuntimeAlgebraReductionRange",
            f"{-runtime_algebra['range'][1]:.1f}--{-runtime_algebra['range'][0]:.1f}\\%",
        ),
        macro("RuntimeCoreMedianChange", f"{runtime_core_median['median']:+.1f}\\%"),
        macro(
            "RuntimeCoreMedianChangeRange",
            f"{runtime_core_median['range'][0]:+.1f}\\% to "
            f"{runtime_core_median['range'][1]:+.1f}\\%",
        ),
        macro(
            "RuntimeTreeSizeRange",
            f"{min(runtime_tree_values) / 1e6:.2f}--{max(runtime_tree_values) / 1e6:.2f} million",
        ),
        macro("NumBoundaryRuns", sum(len(repeat_values(S[s]["runs"], m, "rmse_z_m"))
                                     for s in ("ntu_day_10_drop2x20", "ntu_day_10_drop3x20")
                                     for m in METHODS)),
        macro("NumBoundaryRepeats", 3),
        macro("GravWanderMax", f"{max(grav):.1f}$^\\circ$"),
        macro("MinPath", f"{min(lengths):.0f}\\,m"),
        macro("MaxPath", f"{max(lengths) / 1000:.1f}\\,km"),
        macro("AlignSec", f"{protocol['align_sec']}\\,s"),
        macro("AlignM", f"{protocol['align_m']}\\,m"),
        macro("GZMedian", f"{100 * np.median(g_z - 1):+.1f}\\%"),
        macro("GZAbsMedian", f"{100 * np.median(np.abs(g_z - 1)):.1f}\\%"),
        macro("GZRange", range_text(g_z)),
        macro("GATEMedian", f"{100 * np.median(g_a - 1):+.1f}\\%"),
        macro("GATEAbsMedian", f"{100 * np.median(np.abs(g_a - 1)):.1f}\\%"),
        macro("GATERange", range_text(g_a)),
        macro("EquivMargin", "5\\%"),
        macro("StrictEquivMargin", "2\\%"),
        macro("EquivPZ", fmt_p(tost(g_z))),
        macro("EquivPATE", fmt_p(tost(g_a))),
        macro("EquivPBoth", fmt_p(max(tost(g_z), tost(g_a)))),
        macro(
            "StrictEquivPBoth",
            fmt_p(max(
                equivalence_primary["rmse_z_m"]["posthoc_2pct_tost_p"],
                equivalence_primary["ate_rmse_m"]["posthoc_2pct_tost_p"],
            )),
        ),
        macro("EquivCIZ", mean_ci90_text(g_z)),
        macro("EquivCIATE", mean_ci90_text(g_a)),
        macro(
            "FixGAbsDeltaZMedian",
            f"{equivalence_primary['rmse_z_m']['absolute_difference_m']['median']:.3f}\\,m",
        ),
        macro(
            "FixGAbsDeltaATEMedian",
            f"{equivalence_primary['ate_rmse_m']['absolute_difference_m']['median']:.3f}\\,m",
        ),
        macro(
            "FamilyEquivPBoth",
            fmt_p(max(
                equivalence_family["rmse_z_m"]["formal_5pct_tost_p"],
                equivalence_family["ate_rmse_m"]["formal_5pct_tost_p"],
            )),
        ),
        macro("NumReproSeq", reproduction["rmse_z_m"]["new"]["sequence_units"]),
        macro("ReproEquivCIZ", reported_ci90_text(reproduction["rmse_z_m"]["new"])),
        macro("ReproEquivCIATE", reported_ci90_text(reproduction["ate_rmse_m"]["new"])),
        macro(
            "ReproEquivPBoth",
            f"{max(reproduction['rmse_z_m']['new']['tost_p'], reproduction['ate_rmse_m']['new']['tost_p']):.2g}",
        ),
        macro(
            "ReproStrictEquivPBoth",
            fmt_p(max(
                equivalence_repro["rmse_z_m"]["posthoc_2pct_tost_p"],
                equivalence_repro["ate_rmse_m"]["posthoc_2pct_tost_p"],
            )),
        ),
        macro("HallFixGZMetres", f"{hall_scale['rmse_z_m']['fixg_m']:.4f}"),
        macro("HallFixGZ", f"{hall_scale['rmse_z_m']['relative_pct']:+.1f}\\%"),
        macro(
            "HallFixGZDeltaMm",
            f"{hall_scale['rmse_z_m']['difference_mm']:+.1f}\\,mm",
        ),
        macro("HallFixGATE", f"{hall_scale['ate_rmse_m']['relative_pct']:+.2f}\\%"),
        macro(
            "HallFixGATEDeltaMm",
            f"{hall_scale['ate_rmse_m']['difference_mm']:+.1f}\\,mm",
        ),
        macro("NumLioSamSeq", len(liosam_sequences)),
        macro("NumLioSamRuns", 4 * len(liosam_sequences)),
        macro("LioSamGZRange", range_text2(liosam_g_z)),
        macro("LioSamGATERange", range_text2(liosam_g_ate)),
        macro("LioSamBothZRange", range_text2(liosam_both_z)),
        macro("LioSamBothATERange", range_text2(liosam_both_ate)),
        macro("NumDirNominalRuns", 16),
        macro("NumDirDropFivePairs", int(dir_drop5["paired_repeats"])),
        macro("DirStrongFGZRange", f"{dir_fg_s05_z.min():+.1f}\\% to {dir_fg_s05_z.max():+.1f}\\%"),
        macro("DirMidFGZRange", f"{dir_fg_s2_z.min():+.1f}\\% to {dir_fg_s2_z.max():+.1f}\\%"),
        macro("DirMidFGATERange", f"{dir_fg_s2_ate.min():+.2f}\\% to {dir_fg_s2_ate.max():+.2f}\\%"),
        macro("DirGEATERange", f"{dir_ge_ate.min():+.2f}\\% to {dir_ge_ate.max():+.2f}\\%"),
        macro("DirDropTwoFGZ", f"{dir_drop2['FG-BA_s2']['delta_rmse_z_pct_vs_off']:+.1f}\\%"),
        macro("DirDropTwoFGATE", f"{dir_drop2['FG-BA_s2']['delta_ate_pct_vs_off']:+.1f}\\%"),
        macro("DirDropTwoGEZ", f"{dir_drop2['GE-BA_s2']['delta_rmse_z_pct_vs_off']:+.1f}\\%"),
        macro("DirDropThreeOffZSpread", f"{dir_drop3['FG-BA_off']['rmse_z_m']['relative_range_pct']:.1f}\\%"),
        macro("DirDropThreeFactorZSpread", f"{dir_drop3['FG-BA_s2']['rmse_z_m']['relative_range_pct']:.1f}\\%"),
        macro("DirDropFiveGEZRange", f"{dir_drop5['delta_rmse_z_pct_range'][0]:+.0f}\\% to {dir_drop5['delta_rmse_z_pct_range'][1]:+.0f}\\%"),
        macro("DirDropFiveGEATERange", f"{dir_drop5['delta_ate_pct_range'][0]:+.0f}\\% to {dir_drop5['delta_ate_pct_range'][1]:+.0f}\\%"),
        macro("NumHallDirPairs", int(hall_direction["paired_repeats"])),
        macro("HallDirFGZRange", f"{hall_direction['effects']['FG-BA_rmse_z_factor_effect_pct']['range'][0]:+.1f}\\% to {hall_direction['effects']['FG-BA_rmse_z_factor_effect_pct']['range'][1]:+.1f}\\%"),
        macro("HallDirFGATERange", f"{hall_direction['effects']['FG-BA_ate_factor_effect_pct']['range'][0]:+.1f}\\% to {hall_direction['effects']['FG-BA_ate_factor_effect_pct']['range'][1]:+.1f}\\%"),
        macro("HallDirGEZRange", f"{hall_direction['effects']['GE-BA_rmse_z_factor_effect_pct']['range'][0]:+.1f}\\% to {hall_direction['effects']['GE-BA_rmse_z_factor_effect_pct']['range'][1]:+.1f}\\%"),
        macro("HallDirGEATERange", f"{hall_direction['effects']['GE-BA_ate_factor_effect_pct']['range'][0]:+.1f}\\% to {hall_direction['effects']['GE-BA_ate_factor_effect_pct']['range'][1]:+.1f}\\%"),
        macro("NumDirWeights", 3),
        macro("NumDirTrajectories", len(final_direction)),
        macro("NumDirRepeatsPerCell", 3),
        macro("NumHallDirBeneficialCells", sum(
            final_median("hall", variant, level, "delta_rmse_z_pct_vs_off") < 0
            and final_median("hall", variant, level, "delta_ate_pct_vs_off") < 0
            for variant in ("FG-BA", "GE-BA")
            for level in ("s0p5", "s2", "s5")
        )),
        macro("NumHallDirResetOutcomes", sum(
            final_cell("hall", variant, level)["failed_repeats"]
            for variant in ("FG-BA", "GE-BA")
            for level in ("s0p5", "s2", "s5")
        )),
        macro("TuhhDirFGStrongZ", f"{final_median('tuhh', 'FG-BA', 's0p5', 'delta_rmse_z_pct_vs_off'):+.1f}\\%"),
        macro("TuhhDirFGStrongATE", f"{final_median('tuhh', 'FG-BA', 's0p5', 'delta_ate_pct_vs_off'):+.1f}\\%"),
        macro("TuhhDirGEZTwo", f"{final_median('tuhh', 'GE-BA', 's2', 'delta_rmse_z_pct_vs_off'):+.1f}\\%"),
        macro("TuhhDirGEATETwo", f"{final_median('tuhh', 'GE-BA', 's2', 'delta_ate_pct_vs_off'):+.1f}\\%"),
        macro("NumTuhhDirArcWarnings", sum(
            final_cell("tuhh", variant, level)["arc_warning_repeats"]
            for variant in ("FG-BA", "GE-BA")
            for level in ("s0p5", "s2", "s5")
        )),
        macro("NumHallWindows", int(dropout_windows["analyses"]["hall05_GE-BA_s2_r1"]["summary"]["windows"])),
        macro("NumTuhhWindows", int(dropout_windows["analyses"]["tuhh_GE-BA_s2_r1"]["summary"]["windows"])),
        macro("BAMedianZ", f"{100 * np.median(b_z - 1):+.1f}\\%"),
        macro("BothMedianZ", f"{100 * np.median(gb_z - 1):+.1f}\\%"),
        macro("ProxyBAZ", f"{np.median(proxy_ba):+.1f}~pp" if proxy_ba else None),
        macro("InteractionZ", f"{np.median(iz):+.1f}~pp"),
        macro("InteractionPZ", fmt_p(stats.wilcoxon(iz).pvalue)),
        macro("InteractionATE", f"{np.median(ia):+.1f}~pp"),
        macro("InteractionPATE", fmt_p(stats.wilcoxon(ia).pvalue)),
        macro("HallOnlineEz", f"{hall_ez:.1f}"),
        macro("HallOnlineZMetres", f"{hall_a['rmse_z_m']:.4f}"),
        macro("HallBothZMetres", f"{hall_both['rmse_z_m']:.4f}"),
        macro("HallBothZ", f"{100 * (hall_both['rmse_z_m'] / hall_a['rmse_z_m'] - 1):+.1f}\\%"),
        macro("HallBothATE", f"{100 * (hall_both['ate_rmse_m'] / hall_a['ate_rmse_m'] - 1):+.1f}\\%"),
        macro("DropTwoGZ", f"{effect(S, 'ntu_day_10_drop2x20', 'RED21', 'rmse_z_m', True):+.1f}\\%"),
        macro("DropTwoGATE", f"{effect(S, 'ntu_day_10_drop2x20', 'RED21', 'ate_rmse_m', True):+.1f}\\%"),
        macro("DropThreeGZ", f"{effect(S, 'ntu_day_10_drop3x20', 'RED21', 'rmse_z_m', True):+.1f}\\%"),
        macro("DropThreeGATE", f"{effect(S, 'ntu_day_10_drop3x20', 'RED21', 'ate_rmse_m', True):+.1f}\\%"),
        macro("DropFiveGZ", f"{effect(S, 'ntu_day_10_drop5x20', 'RED21', 'rmse_z_m'):+.1f}\\%"),
        macro("DropFiveGATE", f"{effect(S, 'ntu_day_10_drop5x20', 'RED21', 'ate_rmse_m'):+.1f}\\%"),
        macro("RangeGZ", f"{effect(S, 'ntu_day_10_range20', 'RED21', 'rmse_z_m'):+.1f}\\%"),
        macro("RangeGATE", f"{effect(S, 'ntu_day_10_range20', 'RED21', 'ate_rmse_m'):+.1f}\\%"),
        macro("FovGZ", f"{effect(S, 'ntu_day_10_fov60', 'RED21', 'rmse_z_m'):+.1f}\\%"),
        macro("FovGATE", f"{effect(S, 'ntu_day_10_fov60', 'RED21', 'ate_rmse_m'):+.1f}\\%"),
        macro("NumImuStressRuns", len(stress_sequences) * len(stress_labels) * 2),
        macro("NumImuStressSeq", len(stress_sequences)),
        macro("NumImuStressLevels", len(stress_labels)),
        macro("ImuNoiseMin", "0.01"),
        macro("ImuNoiseMax", "10"),
        macro("ImuDayZMin", f"{day_z.min():+.1f}\\%"),
        macro("ImuDayZMax", f"{day_z.max():+.1f}\\%"),
        macro("ImuNightZMin", f"{night_z.min():+.1f}\\%"),
        macro("ImuNightZMax", f"{night_z.max():+.1f}\\%"),
        macro("ImuDayATEMin", f"{day_ate.min():+.1f}\\%"),
        macro("ImuDayATEMax", f"{day_ate.max():+.1f}\\%"),
        macro("ImuNightATEMin", f"{night_ate.min():+.1f}\\%"),
        macro("ImuNightATEMax", f"{night_ate.max():+.1f}\\%"),
        macro("ImuStressAttMax", f"{max(attitude_delta):.3f}$^\\circ$"),
        macro("NumInitStressRuns", len(init_sequences) * len(init_labels) * 2),
        macro("NumInitStressSeq", len(init_sequences)),
        macro("NumInitStressLevels", len(init_labels)),
        macro(
            "InitStressAngles",
            "$" + "/".join(
                f"{float(label.replace('p', '.')):g}^\\circ"
                for label in init_labels
            ) + "$",
        ),
        macro("InitErrZMin", f"{init_z.min():+.1f}\\%"),
        macro("InitErrZMax", f"{init_z.max():+.1f}\\%"),
        macro("InitErrATEMin", f"{init_ate.min():+.1f}\\%"),
        macro("InitErrATEMax", f"{init_ate.max():+.1f}\\%"),
        macro("InitErrAttMax", f"{max(init_attitude_delta):.3f}$^\\circ$"),
        macro("HhsDropTwoGZ", f"{effect(S, 'tuhh_day_04_drop2x20', 'RED21', 'rmse_z_m'):+.1f}\\%"),
        macro("HhsDropTwoGATE", f"{effect(S, 'tuhh_day_04_drop2x20', 'RED21', 'ate_rmse_m'):+.1f}\\%"),
        macro("HhsDropThreeGZ", f"{effect(S, 'tuhh_day_04_drop3x20', 'RED21', 'rmse_z_m'):+.1f}\\%"),
        macro("HhsDropThreeGATE", f"{effect(S, 'tuhh_day_04_drop3x20', 'RED21', 'ate_rmse_m'):+.1f}\\%"),
        macro("HhsDropFiveGZ", f"{effect(S, 'tuhh_day_04_drop5x20', 'RED21', 'rmse_z_m'):+.1f}\\%"),
        macro("HhsDropFiveGATE", f"{effect(S, 'tuhh_day_04_drop5x20', 'RED21', 'ate_rmse_m'):+.1f}\\%"),
        macro("NumWarmSwitchTraj", len(warm_fixg21["trajectories"])),
        macro("NumWarmRepeatPairs", len(warm_vehicle["repeatability"]["pairs"])),
        macro("NumWarmPhases", len(warm_vehicle["phase_robustness"]["phases"])),
        macro("WarmVehCleanZ", f"{warm_effect(warm_vehicle, 'clean', 'rmse_z_m'):+.2f}\\%"),
        macro("WarmVehCleanATE", f"{warm_effect(warm_vehicle, 'clean', 'ate_rmse_m'):+.2f}\\%"),
        macro("WarmVehDropZ", f"{warm_effect(warm_vehicle, 'dropout', 'rmse_z_m'):+.2f}\\%"),
        macro("WarmVehDropATE", f"{warm_effect(warm_vehicle, 'dropout', 'ate_rmse_m'):+.1f}\\%"),
        macro("WarmHhsCleanZ", f"{warm_effect(warm_handheld, 'clean', 'rmse_z_m'):+.2f}\\%"),
        macro("WarmHhsCleanATE", f"{warm_effect(warm_handheld, 'clean', 'ate_rmse_m'):+.2f}\\%"),
        macro("WarmHhsDropZ", f"{warm_effect(warm_handheld, 'dropout', 'rmse_z_m'):+.2f}\\%"),
        macro("WarmHhsDropATE", f"{warm_effect(warm_handheld, 'dropout', 'ate_rmse_m'):+.1f}\\%"),
        macro("WarmVehZInteraction", f"{warm_interaction_summary(warm_vehicle, 'rmse_z_m', 'repeatability', 'median'):+.2f}\\,m"),
        macro("WarmVehATEInteraction", f"{warm_interaction_summary(warm_vehicle, 'ate_rmse_m', 'repeatability', 'median'):+.2f}\\,m"),
        macro("WarmHhsZInteraction", f"{warm_interaction_summary(warm_handheld, 'rmse_z_m', 'repeatability', 'median'):+.2f}\\,m"),
        macro("WarmHhsATEInteraction", f"{warm_interaction_summary(warm_handheld, 'ate_rmse_m', 'repeatability', 'median'):+.2f}\\,m"),
        macro("WarmVehZInteractionRange", metric_range(warm_interaction_summary(warm_vehicle, 'rmse_z_m', 'repeatability', 'range'), unit="\\,m")),
        macro("WarmVehATEInteractionRange", metric_range(warm_interaction_summary(warm_vehicle, 'ate_rmse_m', 'repeatability', 'range'), unit="\\,m")),
        macro("WarmHhsZInteractionRange", metric_range(warm_interaction_summary(warm_handheld, 'rmse_z_m', 'repeatability', 'range'), unit="\\,m")),
        macro("WarmHhsATEInteractionRange", metric_range(warm_interaction_summary(warm_handheld, 'ate_rmse_m', 'repeatability', 'range'), unit="\\,m")),
        macro("WarmVehPhaseZRange", metric_range(warm_interaction_summary(warm_vehicle, 'rmse_z_m', 'phase_robustness', 'range'), unit="\\,m")),
        macro("WarmVehPhaseATERange", metric_range(warm_interaction_summary(warm_vehicle, 'ate_rmse_m', 'phase_robustness', 'range'), unit="\\,m")),
        macro("WarmHhsPhaseZRange", metric_range(warm_interaction_summary(warm_handheld, 'rmse_z_m', 'phase_robustness', 'range'), unit="\\,m")),
        macro("WarmHhsPhaseATERange", metric_range(warm_interaction_summary(warm_handheld, 'ate_rmse_m', 'phase_robustness', 'range'), unit="\\,m")),
    ]
    (OUT / "stats.tex").write_text("\n".join(lines) + "\n")
    print("stats.tex")


def main():
    S = load()
    which = sys.argv[1] if len(sys.argv) > 1 else "all"
    if which in ("stats", "all"):
        stats_macros(S)
    if which in ("t1", "all"):
        main_table(S)
        nominal_evidence_table(S)
    if which in ("t2", "all"):
        boundary_table(S)
        operating_boundary_table(S)
    if which in ("t3", "all"):
        validity_table(S)
    if which in ("t4", "all"):
        imu_stress_table(S)
    if which in ("t5", "all"):
        direction_factor_table()


if __name__ == "__main__":
    main()
